---
apiVersion: v1
kind: Service
metadata:
  name: webappservice
  namespace: assignment4-grp2
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - protocol: "TCP"
      port: 3200
      targetPort: 3200